import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Reverseword from "./reverseword"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const mostOccured = (arr:Array<any>)=>{
    const obj:any = {}
    let compareCount = 0
    let i;
    let x;
    let mostElement;

    for(i=0; i<arr.length; i++){
      let word = arr[i];
      
      if(obj[word]){
        obj[word] = obj[word] + 1
      }

      else{
        obj[word] = 1
      }

   

    }

    for(x in obj){
      if(obj[x] > compareCount){
        compareCount = obj[x]
        mostElement = x;
        console.log("Most occured", mostElement)
        
      }
    }

    console.log(compareCount)

    console.log(obj)

  }


  mostOccured([1,1,2,3,5,7,9,2,2,2])
  return (
    <>
      <Head>
        <title>Javascript Algorithms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
<Reverseword/>

      

          

    </>
  )
}
